version: '3.8'

services:
  qdrant:
    # 使用官方的 Qdrant 镜像
    image: qdrant/qdrant:latest
    
    # 设置容器的名称，它会读取您 .env 文件中的变量
    container_name: ${CENTRAL_DB_CONTAINER_NAME:-ai-recruiter-qdrant-db}
    
    # 将容器的 6333 端口映射到您电脑的 6333 端口，这样Python脚本才能连接它
    ports:
      - "6335:6333"
      - "6336:6334"
      
    # 这一步非常重要：它会将数据库的数据保存在您项目目录下的 qdrant_storage 文件夹里
    # 这样即使您关闭了容器，数据也不会丢失
    volumes:
      - ./qdrant_storage:/qdrant/storage
      
    # 确保容器总是会自动重启
    restart: always